spring:
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://${spring.datasource.env}:3306/happyhouse?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ssafy
    password: ssafy
    env: 3.37.1.251
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

server:
  port: 8080

kakao:
  url:
    category: https://dapi.kakao.com/v2/local/search/category.json
    address: https://dapi.kakao.com/v2/local/search/address.json
    keyword: https://dapi.kakao.com/v2/local/search/keword.json
  key:
    Authorization: KakaoAK 7fe1b040173a7ec41094ea2ca9879f2b
